Home mentor
2020-1-RDM/Backend pull request #1
Opened 2020-05-20 19:54 UTC by matheustosin

PR com funções de "atualizar mentoria" e "desativar mentoria" referentes à US 5.2.

2020-05-23 22:49 UTC, larissafiorini approved these changes

2020-05-24 13:46 UTC, luisgsantana requested changes

2020-05-25 12:53 UTC, matheustosin reviewed
Mudanças feitas!

2020-05-25 14:09 UTC, luisgsantana approved these changes

2020-05-25 14:09 UTC, merged