Email send
2020-1-RDM/Backend pull request #17
Opened 2020-06-10 12:26 UTC by joaolaureano

Criação de método para envio de email, usando Nodemailer;
Criação de template de email, usando Handlebars;
Integração do método de email com o método do Ardel(mais alguém ?), usado para marcar uma mentoria;

PS: a task pede pra mandar pra IDEAR também, mas achei melhor não pôr agora pra poder testar tranquilo, e adicionar depois. Posso adicionar, de qq forma;
PS²: foi criado uma conta no gmail pra poder usar o Nodemailer, as info dela estão no .env;

2020-06-10 15:09 UTC, alexandrebing requested changes

2020-06-12 14:26 UTC, alexandrebing requested changes
Pra não complicar muito as coisas, já que teríamos que adaptar o getUser da userController ou fazer uma consulta desnecessária, o mais "rápido" seria uma nova função de getUser pelo CPF no modules export do userController... Chamei de getUserCPF mas pode ser outro nome tb, só não pode ser o mesmo getUser.

Assim, em `modules.exports` dentro da nossa userController, colocar a função que antes estava na mentoriaController (renomeada pra não dar conflito com a que existe).

```
async getUserCPF(cpf) {
  const userCollection = db.collection('user');
  let user = null;
  await userCollection
    .where('cpf', '==', cpf)
    .get()
    .then((snapshot) => {
      return snapshot.forEach((res) => {
        user = {
          id: res.id,
          data: res.data(),
        };
      });
    });
  if (!user) {
    return null;
  }
  return user;
}

```

2020-06-12 14:55 UTC, alexandrebing approved these changes

2020-06-13 14:22 UTC, luisgsantana requested changes

2020-06-13 15:11 UTC, luisgsantana approved these changes

2020-06-13 15:22 UTC, merged